{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"manager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateLocations"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/locationmanager\/locationmanager(_:didupdatelocations:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/locationmanager\/locationmanager(_:didupdatelocations:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/LocationManager\/locationManager(_:didUpdateLocations:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CLLocationManagerDelegate.locationManager(_:didUpdateLocations:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"locationManager:didUpdateLocations:"}],"role":"symbol","title":"locationManager(_:didUpdateLocations:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateLocations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@CM@BlinkShelf@objc(cs)LocationManager(im)locationManager:didUpdateLocations:","extendedModule":"BlinkShelf","modules":[{"name":"BlinkShelf"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/LocationManager","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/LocationManager\/CLLocationManagerDelegate-Implementations"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/LocationManager/locationManager(_:didUpdateLocations:)":{"role":"symbol","title":"locationManager(_:didUpdateLocations:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateLocations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/LocationManager\/locationManager(_:didUpdateLocations:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationManager:didUpdateLocations:"}],"url":"\/documentation\/blinkshelf\/locationmanager\/locationmanager(_:didupdatelocations:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/LocationManager":{"role":"symbol","title":"LocationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationManager"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/LocationManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationManager"}],"url":"\/documentation\/blinkshelf\/locationmanager"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/LocationManager/CLLocationManagerDelegate-Implementations":{"role":"collectionGroup","title":"CLLocationManagerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/LocationManager\/CLLocationManagerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/blinkshelf\/locationmanager\/cllocationmanagerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"locationManager:didUpdateLocations:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didUpdateLocations:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"locationManager:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"manager"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateLocations:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<CLLocation *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"locations"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1LocationManager~1locationManager(_:didUpdateLocations:)\/title","value":"locationManager:didUpdateLocations:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1LocationManager~1locationManager(_:didUpdateLocations:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didUpdateLocations:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1LocationManager\/title","value":"LocationManager"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1LocationManager\/fragments","value":[{"kind":"identifier","text":"LocationManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}