{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionResultObjC"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/detectionresultobjc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/detectionresultobjc"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject","doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP","doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/SQ","doc:\/\/com.microblink.ProductRecognition\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/init(params:typeOfDetection:score:left:top:right:bottom:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/bottom","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/left","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/right","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/score","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/top","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/typeOfDetection","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/uid"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionResultObjC"}],"title":"DetectionResultObjC","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)DetectionResultObjC","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"DetectionResultObjC"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/DetectionResultObjC/right":{"role":"symbol","title":"right","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/right","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"right"}],"url":"\/documentation\/blinkshelf\/detectionresultobjc\/right"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/DetectionResultObjC/uid":{"role":"symbol","title":"uid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/uid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"uid"}],"url":"\/documentation\/blinkshelf\/detectionresultobjc\/uid"},"doc://com.microblink.ProductRecognition/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP"},"doc://com.microblink.ProductRecognition/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(cs)NSObject"},"doc://com.microblink.ProductRecognition/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SQ"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/DetectionResultObjC/typeOfDetection":{"role":"symbol","title":"typeOfDetection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeOfDetection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/typeOfDetection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"typeOfDetection"}],"url":"\/documentation\/blinkshelf\/detectionresultobjc\/typeofdetection"},"doc://com.microblink.ProductRecognition/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SH"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/DetectionResultObjC/top":{"role":"symbol","title":"top","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/top","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"top"}],"url":"\/documentation\/blinkshelf\/detectionresultobjc\/top"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/DetectionResultObjC/bottom":{"role":"symbol","title":"bottom","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/bottom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bottom"}],"url":"\/documentation\/blinkshelf\/detectionresultobjc\/bottom"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/DetectionResultObjC/init(params:typeOfDetection:score:left:top:right:bottom:)":{"role":"symbol","title":"init(params:typeOfDetection:score:left:top:right:bottom:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"typeOfDetection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"score"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"top"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/init(params:typeOfDetection:score:left:top:right:bottom:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithParams:typeOfDetection:score:left:top:right:bottom:"}],"url":"\/documentation\/blinkshelf\/detectionresultobjc\/init(params:typeofdetection:score:left:top:right:bottom:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/DetectionResultObjC/left":{"role":"symbol","title":"left","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/left","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"left"}],"url":"\/documentation\/blinkshelf\/detectionresultobjc\/left"},"doc://com.microblink.ProductRecognition/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/DetectionResultObjC":{"role":"symbol","title":"DetectionResultObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionResultObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectionResultObjC"}],"url":"\/documentation\/blinkshelf\/detectionresultobjc"},"doc://com.microblink.ProductRecognition/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP"},"doc://com.microblink.ProductRecognition/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/DetectionResultObjC/score":{"role":"symbol","title":"score","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"score"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/score","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"score"}],"url":"\/documentation\/blinkshelf\/detectionresultobjc\/score"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DetectionResultObjC"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DetectionResultObjC"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DetectionResultObjC"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/bottom","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/left","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/right","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/score","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/top","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/typeOfDetection","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/uid"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectionResultObjC\/init(params:typeOfDetection:score:left:top:right:bottom:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionResultObjC"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1right\/title","value":"right"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1right\/fragments","value":[{"kind":"identifier","text":"right"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1uid\/title","value":"uid"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1uid\/fragments","value":[{"kind":"identifier","text":"uid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1typeOfDetection\/title","value":"typeOfDetection"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1typeOfDetection\/fragments","value":[{"kind":"identifier","text":"typeOfDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1top\/title","value":"top"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1top\/fragments","value":[{"kind":"identifier","text":"top"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1bottom\/title","value":"bottom"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1bottom\/fragments","value":[{"kind":"identifier","text":"bottom"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1init(params:typeOfDetection:score:left:top:right:bottom:)\/title","value":"initWithParams:typeOfDetection:score:left:top:right:bottom:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1init(params:typeOfDetection:score:left:top:right:bottom:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParams:typeOfDetection:score:left:top:right:bottom:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1left\/title","value":"left"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1left\/fragments","value":[{"kind":"identifier","text":"left"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC\/title","value":"DetectionResultObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC\/fragments","value":[{"kind":"identifier","text":"DetectionResultObjC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1score\/title","value":"score"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectionResultObjC~1score\/fragments","value":[{"kind":"identifier","text":"score"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}