{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Installation","level":2,"type":"heading","text":"Installation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"BlinkShelf can be deployed in "},{"type":"strong","inlineContent":[{"type":"text","text":"iOS 13.0 or later"}]},{"type":"text","text":" and can be installed via CocoaPods, Carthage, Swift Package Manager, or manually. For more information, see "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Installation"},{"type":"text","text":"."}]},{"anchor":"Set-up-your-license-key-for-authentication","level":2,"type":"heading","text":"Set up your license key for authentication"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use the license key associated with your app’s bundle identifier."}]}],"type":"aside","name":"Important"},{"type":"codeListing","syntax":"swift","code":["func application(_ application: UIApplication, didFinishLaunchingWithOptions","                 launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","","    SDKManager.setLicenseKey(licenseKey: <license key string>)","  ","  return true","}"]},{"anchor":"Add-Camera-Usage-Description","level":2,"type":"heading","text":"Add Camera Usage Description"},{"type":"paragraph","inlineContent":[{"type":"text","text":"iOS requires that you provide a usage description in order to access the camera. This is essential when using the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/SinglePhotoVC"},{"type":"text","text":" instance included in the package."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"On your app’s "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":", add:"}]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Key"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Value"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Privacy - Camera Usage Description"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Camera access is needed to capture images of products"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Privacy - Photo Library Additions Usage Description"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Allow access to save your photo"}]}]]],"header":"row"},{"anchor":"Add-Location-Access-Description","level":2,"type":"heading","text":"Add Location Access Description"},{"type":"paragraph","inlineContent":[{"type":"text","text":"User location is required to enable BlinkShelf’s "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Store Detection"}]},{"type":"text","text":" feature. iOS requires that you provide a usage description in order to access the user’s location."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"On your app’s "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":", add:"}]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Key"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Value"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Privacy - Location When In Use Usage Description"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"The app uses your location to detect the current store"}]}]]],"header":"row"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/gettingstarted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/gettingstarted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/GettingStarted","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Integrate BlinkShelf to your project and the necessary keys to get started."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Getting Started","role":"article","modules":[{"name":"BlinkShelf"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf"]]},"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Installation","doc:\/\/com.microblink.ProductRecognition\/tutorials\/BlinkShelf"],"generated":true}],"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/SinglePhotoVC":{"role":"symbol","title":"SinglePhotoVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SinglePhotoVC"}],"abstract":[{"type":"text","text":"The easiest way to manage image capture and scanning."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/SinglePhotoVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SinglePhotoVC"}],"url":"\/documentation\/blinkshelf\/singlephotovc"},"doc://com.microblink.ProductRecognition/tutorials/BlinkShelf":{"role":"overview","title":"Using BlinkShelf","abstract":[{"type":"text","text":"BlinkShelf comes with a prebuilt interface to manage capture and scanning that is customizable for your needs."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/tutorials\/BlinkShelf","kind":"overview","type":"topic","url":"\/tutorials\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/Installation":{"role":"article","title":"Installation","abstract":[{"type":"text","text":"Install BlinkShelf via CocoaPods, Carthage, Swift Package Manager, or manually."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Installation","kind":"article","type":"topic","url":"\/documentation\/blinkshelf\/installation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Installation","doc:\/\/com.microblink.ProductRecognition\/tutorials\/BlinkShelf"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1SinglePhotoVC\/title","value":"SinglePhotoVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1SinglePhotoVC\/fragments","value":[{"kind":"identifier","text":"SinglePhotoVC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}