{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageProcessor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/imageprocessor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/imageprocessor"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject","doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP","doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/SQ","doc:\/\/com.microblink.ProductRecognition\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/init(_:embedderVersion:licenseKey:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/feedBuffer(_:buffer:withRotation:withScoreThreshold:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getBgrImageData(forImageUid:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getCVPixelBufferForDetection(withId:forImageUid:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getEmbeddingForDetection(withId:forImageUid:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getEmbeddingForImage(_:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getLatestItemsTrackingData()","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getProcessingData(forImageUid:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getUIImageForDetection(withId:forImageUid:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/removeData(forImageUid:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/resetTrackingState()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageProcessor"}],"title":"ImageProcessor","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ImageProcessor","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"ImageProcessor"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf"]]},"references":{"doc://com.microblink.ProductRecognition/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageProcessor/getEmbeddingForDetection(withId:forImageUid:)":{"role":"symbol","title":"getEmbeddingForDetection(withId:forImageUid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getEmbeddingForDetection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forImageUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getEmbeddingForDetection(withId:forImageUid:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getEmbeddingForDetectionWithId:forImageUid:"}],"url":"\/documentation\/blinkshelf\/imageprocessor\/getembeddingfordetection(withid:forimageuid:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageProcessor/init(_:embedderVersion:licenseKey:)":{"role":"symbol","title":"init(_:embedderVersion:licenseKey:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DetectorVersionObjC","preciseIdentifier":"c:@E@DetectorVersionObjC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"embedderVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EmbedderVersionObjC","preciseIdentifier":"c:@E@EmbedderVersionObjC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"licenseKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/init(_:embedderVersion:licenseKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init:embedderVersion:licenseKey:"}],"url":"\/documentation\/blinkshelf\/imageprocessor\/init(_:embedderversion:licensekey:)"},"doc://com.microblink.ProductRecognition/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SQ"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageProcessor/removeData(forImageUid:)":{"role":"symbol","title":"removeData(forImageUid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forImageUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/removeData(forImageUid:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeDataForImageUid:"}],"url":"\/documentation\/blinkshelf\/imageprocessor\/removedata(forimageuid:)"},"doc://com.microblink.ProductRecognition/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(cs)NSObject"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageProcessor/getBgrImageData(forImageUid:)":{"role":"symbol","title":"getBgrImageData(forImageUid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBgrImageData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forImageUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getBgrImageData(forImageUid:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBgrImageDataForImageUid:"}],"url":"\/documentation\/blinkshelf\/imageprocessor\/getbgrimagedata(forimageuid:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageProcessor/resetTrackingState()":{"role":"symbol","title":"resetTrackingState()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetTrackingState"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/resetTrackingState()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resetTrackingState"}],"url":"\/documentation\/blinkshelf\/imageprocessor\/resettrackingstate()"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageProcessor/getEmbeddingForImage(_:)":{"role":"symbol","title":"getEmbeddingForImage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getEmbeddingForImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getEmbeddingForImage(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getEmbeddingForImage:"}],"url":"\/documentation\/blinkshelf\/imageprocessor\/getembeddingforimage(_:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageProcessor/getUIImageForDetection(withId:forImageUid:)":{"role":"symbol","title":"getUIImageForDetection(withId:forImageUid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUIImageForDetection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forImageUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getUIImageForDetection(withId:forImageUid:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getUIImageForDetectionWithId:forImageUid:"}],"url":"\/documentation\/blinkshelf\/imageprocessor\/getuiimagefordetection(withid:forimageuid:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageProcessor/getProcessingData(forImageUid:)":{"role":"symbol","title":"getProcessingData(forImageUid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getProcessingData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forImageUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ProcessingData","preciseIdentifier":"c:objc(cs)ProcessingData"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getProcessingData(forImageUid:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getProcessingDataForImageUid:"}],"url":"\/documentation\/blinkshelf\/imageprocessor\/getprocessingdata(forimageuid:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageProcessor/feedBuffer(_:buffer:withRotation:withScoreThreshold:)":{"role":"symbol","title":"feedBuffer(_:buffer:withRotation:withScoreThreshold:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"feedBuffer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withRotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBufferOrientation","preciseIdentifier":"c:@E@CVPixelBufferOrientation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withScoreThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/feedBuffer(_:buffer:withRotation:withScoreThreshold:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"feedBuffer:buffer:withRotation:withScoreThreshold:"}],"url":"\/documentation\/blinkshelf\/imageprocessor\/feedbuffer(_:buffer:withrotation:withscorethreshold:)"},"doc://com.microblink.ProductRecognition/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SH"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageProcessor/getLatestItemsTrackingData()":{"role":"symbol","title":"getLatestItemsTrackingData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLatestItemsTrackingData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"TrackedDataObjC","preciseIdentifier":"c:objc(cs)TrackedDataObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getLatestItemsTrackingData()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getLatestItemsTrackingData"}],"url":"\/documentation\/blinkshelf\/imageprocessor\/getlatestitemstrackingdata()"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageProcessor/getCVPixelBufferForDetection(withId:forImageUid:)":{"role":"symbol","title":"getCVPixelBufferForDetection(withId:forImageUid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCVPixelBufferForDetection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forImageUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Unmanaged","preciseIdentifier":"s:s9UnmanagedV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getCVPixelBufferForDetection(withId:forImageUid:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getCVPixelBufferForDetectionWithId:forImageUid:"}],"url":"\/documentation\/blinkshelf\/imageprocessor\/getcvpixelbufferfordetection(withid:forimageuid:)"},"doc://com.microblink.ProductRecognition/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP"},"doc://com.microblink.ProductRecognition/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageProcessor":{"role":"symbol","title":"ImageProcessor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageProcessor"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageProcessor"}],"url":"\/documentation\/blinkshelf\/imageprocessor"},"doc://com.microblink.ProductRecognition/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ImageProcessor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ImageProcessor"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ImageProcessor"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/feedBuffer(_:buffer:withRotation:withScoreThreshold:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getBgrImageData(forImageUid:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getCVPixelBufferForDetection(withId:forImageUid:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getEmbeddingForDetection(withId:forImageUid:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getEmbeddingForImage(_:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getLatestItemsTrackingData()","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getProcessingData(forImageUid:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/getUIImageForDetection(withId:forImageUid:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/init(_:embedderVersion:licenseKey:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/removeData(forImageUid:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageProcessor\/resetTrackingState()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageProcessor"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1getEmbeddingForDetection(withId:forImageUid:)\/title","value":"getEmbeddingForDetectionWithId:forImageUid:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1getEmbeddingForDetection(withId:forImageUid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getEmbeddingForDetectionWithId:forImageUid:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1init(_:embedderVersion:licenseKey:)\/title","value":"init:embedderVersion:licenseKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1init(_:embedderVersion:licenseKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init:embedderVersion:licenseKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1removeData(forImageUid:)\/title","value":"removeDataForImageUid:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1removeData(forImageUid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeDataForImageUid:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1getBgrImageData(forImageUid:)\/title","value":"getBgrImageDataForImageUid:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1getBgrImageData(forImageUid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBgrImageDataForImageUid:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1resetTrackingState()\/title","value":"resetTrackingState"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1resetTrackingState()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetTrackingState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1getEmbeddingForImage(_:)\/title","value":"getEmbeddingForImage:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1getEmbeddingForImage(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getEmbeddingForImage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1getUIImageForDetection(withId:forImageUid:)\/title","value":"getUIImageForDetectionWithId:forImageUid:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1getUIImageForDetection(withId:forImageUid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUIImageForDetectionWithId:forImageUid:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1getProcessingData(forImageUid:)\/title","value":"getProcessingDataForImageUid:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1getProcessingData(forImageUid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getProcessingDataForImageUid:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1feedBuffer(_:buffer:withRotation:withScoreThreshold:)\/title","value":"feedBuffer:buffer:withRotation:withScoreThreshold:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1feedBuffer(_:buffer:withRotation:withScoreThreshold:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"feedBuffer:buffer:withRotation:withScoreThreshold:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1getLatestItemsTrackingData()\/title","value":"getLatestItemsTrackingData"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1getLatestItemsTrackingData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLatestItemsTrackingData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1getCVPixelBufferForDetection(withId:forImageUid:)\/title","value":"getCVPixelBufferForDetectionWithId:forImageUid:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor~1getCVPixelBufferForDetection(withId:forImageUid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCVPixelBufferForDetectionWithId:forImageUid:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor\/title","value":"ImageProcessor"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageProcessor\/fragments","value":[{"kind":"identifier","text":"ImageProcessor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}