{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageUtilsObjCpp"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/imageutilsobjcpp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/imageutilsobjcpp"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject","doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP","doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/SQ","doc:\/\/com.microblink.ProductRecognition\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageUtilsObjCpp","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageUtilsObjCpp\/createCVPixelBuffer(from:width:height:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageUtilsObjCpp\/createData(fromBGRBytes:count:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageUtilsObjCpp\/createUIImage(from:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageUtilsObjCpp"}],"title":"ImageUtilsObjCpp","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ImageUtilsObjCpp","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"ImageUtilsObjCpp"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf"]]},"references":{"doc://com.microblink.ProductRecognition/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SH"},"doc://com.microblink.ProductRecognition/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SQ"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageUtilsObjCpp/createUIImage(from:)":{"role":"symbol","title":"createUIImage(from:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createUIImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageUtilsObjCpp\/createUIImage(from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createUIImageFromCVPixelBuffer:"}],"url":"\/documentation\/blinkshelf\/imageutilsobjcpp\/createuiimage(from:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(cs)NSObject"},"doc://com.microblink.ProductRecognition/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP"},"doc://com.microblink.ProductRecognition/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject"},"doc://com.microblink.ProductRecognition/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageUtilsObjCpp/createCVPixelBuffer(from:width:height:)":{"role":"symbol","title":"createCVPixelBuffer(from:width:height:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCVPixelBuffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Unmanaged","preciseIdentifier":"s:s9UnmanagedV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageUtilsObjCpp\/createCVPixelBuffer(from:width:height:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createCVPixelBufferFromData:width:height:"}],"url":"\/documentation\/blinkshelf\/imageutilsobjcpp\/createcvpixelbuffer(from:width:height:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageUtilsObjCpp":{"role":"symbol","title":"ImageUtilsObjCpp","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageUtilsObjCpp"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageUtilsObjCpp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageUtilsObjCpp"}],"url":"\/documentation\/blinkshelf\/imageutilsobjcpp"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageUtilsObjCpp/createData(fromBGRBytes:count:)":{"role":"symbol","title":"createData(fromBGRBytes:count:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromBGRBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageUtilsObjCpp\/createData(fromBGRBytes:count:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createDataFromBGRBytes:count:"}],"url":"\/documentation\/blinkshelf\/imageutilsobjcpp\/createdata(frombgrbytes:count:)"},"doc://com.microblink.ProductRecognition/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ImageUtilsObjCpp"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ImageUtilsObjCpp"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ImageUtilsObjCpp"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageUtilsObjCpp\/createCVPixelBuffer(from:width:height:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageUtilsObjCpp\/createData(fromBGRBytes:count:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageUtilsObjCpp\/createUIImage(from:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageUtilsObjCpp"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageUtilsObjCpp~1createUIImage(from:)\/title","value":"createUIImageFromCVPixelBuffer:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageUtilsObjCpp~1createUIImage(from:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createUIImageFromCVPixelBuffer:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageUtilsObjCpp~1createCVPixelBuffer(from:width:height:)\/title","value":"createCVPixelBufferFromData:width:height:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageUtilsObjCpp~1createCVPixelBuffer(from:width:height:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createCVPixelBufferFromData:width:height:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageUtilsObjCpp\/title","value":"ImageUtilsObjCpp"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageUtilsObjCpp\/fragments","value":[{"kind":"identifier","text":"ImageUtilsObjCpp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageUtilsObjCpp~1createData(fromBGRBytes:count:)\/title","value":"createDataFromBGRBytes:count:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageUtilsObjCpp~1createData(fromBGRBytes:count:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createDataFromBGRBytes:count:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}