{"primaryContentSections":[{"kind":"content","content":[{"anchor":"CocoaPods","level":2,"type":"heading","text":"CocoaPods"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/cocoapods.org"},{"type":"text","text":" is a dependency manager for Swift and Objective-C projects. For usage and installation instructions, visit their website."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here is a sample barebones "},{"type":"codeVoice","code":"Podfile"},{"type":"text","text":" which imports the "},{"type":"codeVoice","code":"BlinkShelf"},{"type":"text","text":" pod:"}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You must include "},{"type":"codeVoice","code":"https:\/\/github.com\/microblink\/PodSpecRepo.git"},{"type":"text","text":" as source as the BlinkShelf pod is hosted in a private spec repository."}]}],"type":"aside","name":"Important"},{"type":"codeListing","syntax":"shell","code":["source 'https:\/\/github.com\/microblink\/PodSpecRepo.git'","source 'https:\/\/cdn.cocoapods.org\/'","","platform :ios, '13.0'","","target 'YourTarget' do","    use_frameworks!","","    pod 'BlinkShelf'","end"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"After editing your "},{"type":"codeVoice","code":"Podfile"},{"type":"text","text":", run "},{"type":"codeVoice","code":"pod install"},{"type":"text","text":" and then open the generated "},{"type":"codeVoice","code":".xcworkspace"},{"type":"text","text":" file instead of "},{"type":"codeVoice","code":".xcodeproj"},{"type":"text","text":"."}]},{"anchor":"Carthage","level":2,"type":"heading","text":"Carthage"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/Carthage\/Carthage"},{"type":"text","text":" is a decentralized dependency manager that builds your dependencies and provides you with binary frameworks, but you retain full control over your project structure and setup. Carthage does not automatically modify your project files or your build settings."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To integrate BlinkShelf into your Xcode project using Carthage, specify it in your "},{"type":"codeVoice","code":"Cartfile"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"shell","code":["binary \"https:\/\/raw.githubusercontent.com\/microblink\/blinkshelf-sdk-ios\/main\/BlinkShelf.json\" ~> 1.0"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"After editing your "},{"type":"codeVoice","code":"Cartfile"},{"type":"text","text":", run "},{"type":"codeVoice","code":"carthage update --use-xcframeworks"},{"type":"text","text":" and then add "},{"type":"codeVoice","code":"BlinkShelf.xcframework"},{"type":"text","text":" to your project. It should be located at "},{"type":"codeVoice","code":"~\/Carthage\/Build\/"},{"type":"text","text":"."}]},{"anchor":"Swift-Package-Manager","level":3,"type":"heading","text":"Swift Package Manager"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"https:\/\/www.swift.org\/package-manager\/"},{"type":"text","text":" is a tool for managing the distribution of Swift code. It’s integrated with the Swift build system to automate the process of downloading, compiling, and linking dependencies."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In Xcode, navigate to "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"File > Add Packages"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Go to "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Search or Enter Package URL"}]}]},{"type":"text","text":" at the top-right search bar of the window that appears, then type:"}]},{"type":"codeListing","syntax":"http","code":["https:\/\/github.com\/microblink\/blinkshelf-sdk-ios.git"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Select "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Up to Next Major Version"}]}]},{"type":"text","text":" on the "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"“Dependency Rule”"}]}]},{"type":"text","text":" and type "},{"type":"codeVoice","code":"1.0.0"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Click "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Add Package"}]}]}]},{"anchor":"Manual-Installation","level":2,"type":"heading","text":"Manual Installation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you prefer not to use any dependency managers, you can integrate BlinkShelf into your project manually."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you haven’t initialized your project as a git repository, open "},{"type":"strong","inlineContent":[{"type":"text","text":"Terminal"}]},{"type":"text","text":" and go to the root of your project directory. Run this command:"}]},{"type":"codeListing","syntax":"shell","code":["$ git init"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Add BlinkShelf as a "},{"type":"reference","isActive":true,"identifier":"https:\/\/git-scm.com\/docs\/git-submodule"},{"type":"text","text":" by running the command:"}]},{"type":"codeListing","syntax":"shell","code":["$ git submodule add https:\/\/github.com\/microblink\/blinkshelf-sdk-ios.git"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Open the new "},{"type":"codeVoice","code":"blinkshelf-sdk-ios"},{"type":"text","text":" folder and drag "},{"type":"codeVoice","code":"BlinkShelf.xcframework"},{"type":"text","text":" into the Project Navigator of your application’s Xcode project."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Select "},{"type":"codeVoice","code":"BlinkShelf.xcframework"},{"type":"text","text":" in the Project Navigator and verify that the deployment target matches that of your application target."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Next, select your application project in the Project Navigator (blue project icon) to navigate to the target configuration window and select the application target under the "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"“Targets”"}]}]},{"type":"text","text":" heading in the sidebar."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In the tab bar at the top of that window, open the "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"“General”"}]}]},{"type":"text","text":" panel and click on the "},{"type":"codeVoice","code":"+"},{"type":"text","text":" button under the "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"“Frameworks, Libraries, and Embedded Content”"}]}]},{"type":"text","text":" section."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"On the window that shows, search for “BlinkShelf”. Select "},{"type":"codeVoice","code":"BlinkShelf.xcframework"},{"type":"text","text":" from the list then click "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Add"}]}]},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"On the table’s "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"“Embed”"}]}]},{"type":"text","text":" column, make sure that "},{"type":"codeVoice","code":"Embed & Sign"},{"type":"text","text":" is selected."}]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Name"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Embed"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"BlinkShelf.xcframework"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Embed & Sign"}]}]]],"header":"row"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/installation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/installation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Installation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Install BlinkShelf via CocoaPods, Carthage, Swift Package Manager, or manually."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Installation","role":"article","modules":[{"name":"BlinkShelf"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf"]]},"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/GettingStarted","doc:\/\/com.microblink.ProductRecognition\/tutorials\/BlinkShelf"],"generated":true}],"references":{"doc://com.microblink.ProductRecognition/tutorials/BlinkShelf":{"role":"overview","title":"Using BlinkShelf","abstract":[{"type":"text","text":"BlinkShelf comes with a prebuilt interface to manage capture and scanning that is customizable for your needs."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/tutorials\/BlinkShelf","kind":"overview","type":"topic","url":"\/tutorials\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"https://cocoapods.org":{"title":"CocoaPods","titleInlineContent":[{"type":"text","text":"CocoaPods"}],"type":"link","identifier":"https:\/\/cocoapods.org","url":"https:\/\/cocoapods.org"},"https://www.swift.org/package-manager/":{"title":"Swift Package Manager","titleInlineContent":[{"type":"text","text":"Swift Package Manager"}],"type":"link","identifier":"https:\/\/www.swift.org\/package-manager\/","url":"https:\/\/www.swift.org\/package-manager\/"},"https://git-scm.com/docs/git-submodule":{"title":"submodule","titleInlineContent":[{"type":"text","text":"submodule"}],"type":"link","identifier":"https:\/\/git-scm.com\/docs\/git-submodule","url":"https:\/\/git-scm.com\/docs\/git-submodule"},"https://github.com/Carthage/Carthage":{"title":"Carthage","titleInlineContent":[{"type":"text","text":"Carthage"}],"type":"link","identifier":"https:\/\/github.com\/Carthage\/Carthage","url":"https:\/\/github.com\/Carthage\/Carthage"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/GettingStarted":{"role":"article","title":"Getting Started","abstract":[{"type":"text","text":"Integrate BlinkShelf to your project and the necessary keys to get started."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/GettingStarted","kind":"article","type":"topic","url":"\/documentation\/blinkshelf\/gettingstarted"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/GettingStarted","doc:\/\/com.microblink.ProductRecognition\/tutorials\/BlinkShelf"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}