{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Item2dTrackingDataObjC"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/item2dtrackingdataobjc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/item2dtrackingdataobjc"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject","doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP","doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/SQ","doc:\/\/com.microblink.ProductRecognition\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/init(params:left:top:right:bottom:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/bottom","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/index","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/left","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/right","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/top"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Item2dTrackingDataObjC"}],"title":"Item2dTrackingDataObjC","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)Item2dTrackingDataObjC","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"Item2dTrackingDataObjC"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf"]]},"references":{"doc://com.microblink.ProductRecognition/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP"},"doc://com.microblink.ProductRecognition/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/Item2dTrackingDataObjC/right":{"role":"symbol","title":"right","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/right","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"right"}],"url":"\/documentation\/blinkshelf\/item2dtrackingdataobjc\/right"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/Item2dTrackingDataObjC/bottom":{"role":"symbol","title":"bottom","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/bottom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bottom"}],"url":"\/documentation\/blinkshelf\/item2dtrackingdataobjc\/bottom"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/Item2dTrackingDataObjC/left":{"role":"symbol","title":"left","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/left","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"left"}],"url":"\/documentation\/blinkshelf\/item2dtrackingdataobjc\/left"},"doc://com.microblink.ProductRecognition/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/Item2dTrackingDataObjC/init(params:left:top:right:bottom:)":{"role":"symbol","title":"init(params:left:top:right:bottom:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"top"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/init(params:left:top:right:bottom:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithParams:left:top:right:bottom:"}],"url":"\/documentation\/blinkshelf\/item2dtrackingdataobjc\/init(params:left:top:right:bottom:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/Item2dTrackingDataObjC/top":{"role":"symbol","title":"top","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/top","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"top"}],"url":"\/documentation\/blinkshelf\/item2dtrackingdataobjc\/top"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/Item2dTrackingDataObjC":{"role":"symbol","title":"Item2dTrackingDataObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Item2dTrackingDataObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Item2dTrackingDataObjC"}],"url":"\/documentation\/blinkshelf\/item2dtrackingdataobjc"},"doc://com.microblink.ProductRecognition/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(cs)NSObject"},"doc://com.microblink.ProductRecognition/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SH"},"doc://com.microblink.ProductRecognition/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SQ"},"doc://com.microblink.ProductRecognition/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/Item2dTrackingDataObjC/index":{"role":"symbol","title":"index","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/index","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"index"}],"url":"\/documentation\/blinkshelf\/item2dtrackingdataobjc\/index"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Item2dTrackingDataObjC"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Item2dTrackingDataObjC"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Item2dTrackingDataObjC"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/bottom","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/index","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/left","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/right","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/top"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Item2dTrackingDataObjC\/init(params:left:top:right:bottom:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Item2dTrackingDataObjC"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Item2dTrackingDataObjC~1right\/title","value":"right"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Item2dTrackingDataObjC~1right\/fragments","value":[{"kind":"identifier","text":"right"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Item2dTrackingDataObjC~1bottom\/title","value":"bottom"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Item2dTrackingDataObjC~1bottom\/fragments","value":[{"kind":"identifier","text":"bottom"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Item2dTrackingDataObjC~1left\/title","value":"left"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Item2dTrackingDataObjC~1left\/fragments","value":[{"kind":"identifier","text":"left"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Item2dTrackingDataObjC~1init(params:left:top:right:bottom:)\/title","value":"initWithParams:left:top:right:bottom:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Item2dTrackingDataObjC~1init(params:left:top:right:bottom:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParams:left:top:right:bottom:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Item2dTrackingDataObjC~1top\/title","value":"top"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Item2dTrackingDataObjC~1top\/fragments","value":[{"kind":"identifier","text":"top"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Item2dTrackingDataObjC\/title","value":"Item2dTrackingDataObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Item2dTrackingDataObjC\/fragments","value":[{"kind":"identifier","text":"Item2dTrackingDataObjC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Item2dTrackingDataObjC~1index\/title","value":"index"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Item2dTrackingDataObjC~1index\/fragments","value":[{"kind":"identifier","text":"index"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}