{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBanner"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/resultbanner"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/resultbanner"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSCoding","doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject","doc:\/\/com.microblink.ProductRecognition\/objc(pl)CALayerDelegate","doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP","doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/SQ","doc:\/\/com.microblink.ProductRecognition\/SH","doc:\/\/com.microblink.ProductRecognition\/s8SendableP","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearance","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearanceContainer","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UICoordinateSpace","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIDynamicItem","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusEnvironment","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusItem","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusItemContainer","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UILargeContentViewerItem","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITraitEnvironment","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A view that displays the preview of a result."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBanner"}],"title":"ResultBanner","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@BlinkShelf@objc(cs)ResultBanner","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"ResultBanner"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/init(frame:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/contentView","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/detailLabel","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/didTapBanner","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/highlightedLabel","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/highlightedView","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/imageView","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/product","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/promo","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/subtitleLabel","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/tagImageView","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/tagView","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/layoutSubviews()","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/loadProduct(_:withPromotionAtIndex:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/bannerHeight"]}],"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/tagImageView":{"role":"symbol","title":"tagImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view of the tag icon."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/tagImageView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultbanner\/tagimageview"},"doc://com.microblink.ProductRecognition/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIDynamicItem"},"doc://com.microblink.ProductRecognition/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusItemContainer"},"doc://com.microblink.ProductRecognition/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/didTapBanner":{"role":"symbol","title":"didTapBanner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapBanner"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Promo","preciseIdentifier":"s:10BlinkShelf5PromoV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"A block to be executed when the result banner is tapped."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/didTapBanner","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultbanner\/didtapbanner"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner":{"role":"symbol","title":"ResultBanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBanner"}],"abstract":[{"type":"text","text":"A view that displays the preview of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBanner"}],"url":"\/documentation\/blinkshelf\/resultbanner"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/contentView":{"role":"symbol","title":"contentView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The content view of the result banner."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/contentView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultbanner\/contentview"},"doc://com.microblink.ProductRecognition/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.microblink.ProductRecognition/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/loadProduct(_:withPromotionAtIndex:)":{"role":"symbol","title":"loadProduct(_:withPromotionAtIndex:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadProduct"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ProductInfo","preciseIdentifier":"s:10BlinkShelf11ProductInfoV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withPromotionAtIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Loads the information of the product to display."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/loadProduct(_:withPromotionAtIndex:)","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultbanner\/loadproduct(_:withpromotionatindex:)"},"doc://com.microblink.ProductRecognition/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject"},"doc://com.microblink.ProductRecognition/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITraitEnvironment"},"doc://com.microblink.ProductRecognition/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UICoordinateSpace"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/highlightedView":{"role":"symbol","title":"highlightedView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightedView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view that highlights the promotion shown at the top of the result banner."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/highlightedView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultbanner\/highlightedview"},"doc://com.microblink.ProductRecognition/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SH"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/blinkshelf\/resultbanner\/layoutsubviews()"},"doc://com.microblink.ProductRecognition/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIView"},"doc://com.microblink.ProductRecognition/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)CALayerDelegate"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that contains the primary text."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/titleLabel","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultbanner\/titlelabel"},"doc://com.microblink.ProductRecognition/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSCoding"},"doc://com.microblink.ProductRecognition/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.microblink.ProductRecognition/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.microblink.ProductRecognition\/s8SendableP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/subtitleLabel":{"role":"symbol","title":"subtitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that contains the secondary text."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/subtitleLabel","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultbanner\/subtitlelabel"},"doc://com.microblink.ProductRecognition/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/product":{"role":"symbol","title":"product","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"product"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProductInfo","preciseIdentifier":"s:10BlinkShelf11ProductInfoV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The information of the product to display."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/product","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultbanner\/product"},"doc://com.microblink.ProductRecognition/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIUserActivityRestoring"},"doc://com.microblink.ProductRecognition/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearanceContainer"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/detailLabel":{"role":"symbol","title":"detailLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that contains the supplementary text."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/detailLabel","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultbanner\/detaillabel"},"doc://com.microblink.ProductRecognition/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIResponderStandardEditActions"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/blinkshelf\/resultbanner\/init(frame:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/promo":{"role":"symbol","title":"promo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"promo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Promo","preciseIdentifier":"s:10BlinkShelf5PromoV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The information of the promotion to display."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/promo","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultbanner\/promo"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/highlightedLabel":{"role":"symbol","title":"highlightedLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightedLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label of the highlighted view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/highlightedLabel","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultbanner\/highlightedlabel"},"doc://com.microblink.ProductRecognition/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP"},"doc://com.microblink.ProductRecognition/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusEnvironment"},"doc://com.microblink.ProductRecognition/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusItem"},"doc://com.microblink.ProductRecognition/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearance"},"doc://com.microblink.ProductRecognition/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SQ"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAccessibilityIdentification"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/imageView":{"role":"symbol","title":"imageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view of the result banner."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/imageView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultbanner\/imageview"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/bannerHeight":{"role":"symbol","title":"bannerHeight","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bannerHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The ideal height of the result banner."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/bannerHeight","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultbanner\/bannerheight"},"doc://com.microblink.ProductRecognition/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UILargeContentViewerItem"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBanner/tagView":{"role":"symbol","title":"tagView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view that contains the tag image view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/tagView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultbanner\/tagview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ResultBanner"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ResultBanner"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ResultBanner"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/init(frame:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBanner\/layoutSubviews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBanner"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultBanner\/title","value":"ResultBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultBanner\/fragments","value":[{"kind":"identifier","text":"ResultBanner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultBanner~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultBanner~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultBanner~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultBanner~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}