{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsVC"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/resultdetailsvc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/resultdetailsvc"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSCoding","doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject","doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP","doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/SQ","doc:\/\/com.microblink.ProductRecognition\/SH","doc:\/\/com.microblink.ProductRecognition\/s8SendableP","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearanceContainer","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIContentContainer","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusEnvironment","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIStateRestoring","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITraitEnvironment","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A view controller that displays the details of a result."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsVC"}],"title":"ResultDetailsVC","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@BlinkShelf@objc(cs)ResultDetailsVC","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"ResultDetailsVC"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/cardView","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/detailHeaderIconView","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/detailHeaderLabel","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/detailHeaderView","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/detailLabel","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/detailView","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/didDismiss","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/dismissButton","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/highlightedLabel","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/highlightedView","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/photoView","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/promo","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/scrollView","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/tagImageView","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/tagView","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/loadPromoDetails(of:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/viewDidLayoutSubviews()","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/viewDidLoad()"]}],"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/highlightedLabel":{"role":"symbol","title":"highlightedLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightedLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label of the highlighted view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/highlightedLabel","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/highlightedlabel"},"doc://com.microblink.ProductRecognition/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.microblink.ProductRecognition/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SQ"},"doc://com.microblink.ProductRecognition/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.microblink.ProductRecognition\/s8SendableP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/photoView":{"role":"symbol","title":"photoView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view that displays the photo of the promotion."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/photoView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/photoview"},"doc://com.microblink.ProductRecognition/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITraitEnvironment"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIResponderStandardEditActions"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/highlightedView":{"role":"symbol","title":"highlightedView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightedView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view that is highlighted at the top of the view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/highlightedView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/highlightedview"},"doc://com.microblink.ProductRecognition/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSExtensionRequestHandling"},"doc://com.microblink.ProductRecognition/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SH"},"doc://com.microblink.ProductRecognition/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/blinkshelf\/resultdetailsvc\/initwithcoder:"},"doc://com.microblink.ProductRecognition/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/dismissButton":{"role":"symbol","title":"dismissButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"abstract":[{"type":"text","text":"The button that dismisses the view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/dismissButton","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/dismissbutton"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that contains the primary text."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/titleLabel","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/titlelabel"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/tagImageView":{"role":"symbol","title":"tagImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view of the tag icon."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/tagImageView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/tagimageview"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/loadPromoDetails(of:)":{"role":"symbol","title":"loadPromoDetails(of:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadPromoDetails"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Promo","preciseIdentifier":"s:10BlinkShelf5PromoV"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Loads the promotion details to display."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/loadPromoDetails(of:)","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/loadpromodetails(of:)"},"doc://com.microblink.ProductRecognition/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearanceContainer"},"doc://com.microblink.ProductRecognition/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIUserActivityRestoring"},"doc://com.microblink.ProductRecognition/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC":{"role":"symbol","title":"ResultDetailsVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsVC"}],"abstract":[{"type":"text","text":"A view controller that displays the details of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultDetailsVC"}],"url":"\/documentation\/blinkshelf\/resultdetailsvc"},"doc://com.microblink.ProductRecognition/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/viewDidLayoutSubviews()":{"role":"symbol","title":"viewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/viewDidLayoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"url":"\/documentation\/blinkshelf\/resultdetailsvc\/viewdidlayoutsubviews()"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/cardView":{"role":"symbol","title":"cardView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view that contains the result details."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/cardView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/cardview"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/blinkshelf\/resultdetailsvc\/initwithnibname:bundle:"},"doc://com.microblink.ProductRecognition/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSCoding"},"doc://com.microblink.ProductRecognition/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIStateRestoring"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/detailHeaderView":{"role":"symbol","title":"detailHeaderView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailHeaderView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view that contains the detail header."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/detailHeaderView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/detailheaderview"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/detailHeaderLabel":{"role":"symbol","title":"detailHeaderLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailHeaderLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label of the text on the detail header."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/detailHeaderLabel","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/detailheaderlabel"},"doc://com.microblink.ProductRecognition/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusEnvironment"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/didDismiss":{"role":"symbol","title":"didDismiss","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDismiss"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The block to be executed when the view is dismissed."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/didDismiss","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/diddismiss"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/detailView":{"role":"symbol","title":"detailView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view that contains the detail label."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/detailView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/detailview"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/detailHeaderIconView":{"role":"symbol","title":"detailHeaderIconView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailHeaderIconView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view of the icon on the detail header."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/detailHeaderIconView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/detailheadericonview"},"doc://com.microblink.ProductRecognition/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP"},"doc://com.microblink.ProductRecognition/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIViewController"},"doc://com.microblink.ProductRecognition/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIContentContainer"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/detailLabel":{"role":"symbol","title":"detailLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that contains the supplementary text."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/detailLabel","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/detaillabel"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/tagView":{"role":"symbol","title":"tagView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view that contains the tag image view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/tagView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/tagview"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/promo":{"role":"symbol","title":"promo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"promo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Promo","preciseIdentifier":"s:10BlinkShelf5PromoV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The information of the promotion to display"}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/promo","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/promo"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/scrollView":{"role":"symbol","title":"scrollView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"}],"abstract":[{"type":"text","text":"The view that allows the scrolling of its contained result details."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/scrollView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultdetailsvc\/scrollview"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultDetailsVC/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/blinkshelf\/resultdetailsvc\/viewdidload()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ResultDetailsVC"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ResultDetailsVC"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ResultDetailsVC"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/initWithCoder:","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/initWithNibName:bundle:","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/viewDidLayoutSubviews()","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultDetailsVC\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsVC"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultDetailsVC\/title","value":"ResultDetailsVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultDetailsVC\/fragments","value":[{"kind":"identifier","text":"ResultDetailsVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultDetailsVC~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultDetailsVC~1viewDidLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultDetailsVC~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultDetailsVC~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}