{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/resultlistview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/resultlistview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSCoding","doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject","doc:\/\/com.microblink.ProductRecognition\/objc(pl)CALayerDelegate","doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP","doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/SQ","doc:\/\/com.microblink.ProductRecognition\/SH","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearance","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearanceContainer","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UICoordinateSpace","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIDynamicItem","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusEnvironment","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusItem","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusItemContainer","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UILargeContentViewerItem","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIScrollViewDelegate","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITableViewDataSource","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITableViewDelegate","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITraitEnvironment","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A view that displays a list of results."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListView"}],"title":"ResultListView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@BlinkShelf@objc(cs)ResultListView","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"ResultListView"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/init(frame:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/cardHandleBar","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/cardHiddenHeight","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/cardShownHeight","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/cardView","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/didSelectPromo","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/didTapCard","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/draggingCard","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/isShown","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/products","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/store","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/summaryLabel","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/summaryText","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/tableView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/layoutSubviews()","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/loadList(of:store:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/UITableViewDataSource-Implementations","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/UITableViewDelegate-Implementations"],"generated":true}],"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/Store":{"role":"symbol","title":"Store","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Store"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Store","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Store"}],"url":"\/documentation\/blinkshelf\/store"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/cardHandleBar":{"role":"symbol","title":"cardHandleBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardHandleBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The bar at the top of the card view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/cardHandleBar","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/cardhandlebar"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/blinkshelf\/resultlistview\/layoutsubviews()"},"doc://com.microblink.ProductRecognition/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UILargeContentViewerItem"},"doc://com.microblink.ProductRecognition/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/blinkshelf\/resultlistview\/init(frame:)"},"doc://com.microblink.ProductRecognition/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIScrollViewDelegate"},"doc://com.microblink.ProductRecognition/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITraitEnvironment"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/store":{"role":"symbol","title":"store","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"store"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Store","preciseIdentifier":"s:10BlinkShelf5StoreV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The current "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Store"},{"type":"text","text":" the user is in, if set."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/store","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/store"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/isShown":{"role":"symbol","title":"isShown","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isShown"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"The display state of the result list."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/isShown","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/isshown"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/didSelectPromo":{"role":"symbol","title":"didSelectPromo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectPromo"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Promo","preciseIdentifier":"s:10BlinkShelf5PromoV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The block to execute when a row is selected from the result list."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/didSelectPromo","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/didselectpromo"},"doc://com.microblink.ProductRecognition/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SQ"},"doc://com.microblink.ProductRecognition/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearanceContainer"},"doc://com.microblink.ProductRecognition/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSCoding"},"doc://com.microblink.ProductRecognition/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SH"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/summaryLabel":{"role":"symbol","title":"summaryLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"summaryLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label of the summary text."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/summaryLabel","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/summarylabel"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/cardHiddenHeight":{"role":"symbol","title":"cardHiddenHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardHiddenHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The ideal height of the card view when the result list is hidden."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/cardHiddenHeight","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/cardhiddenheight"},"doc://com.microblink.ProductRecognition/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusItemContainer"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/UITableViewDataSource-Implementations":{"role":"collectionGroup","title":"UITableViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/UITableViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/uitableviewdatasource-implementations"},"doc://com.microblink.ProductRecognition/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UIKit.UITableViewDataSource","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITableViewDataSource"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/tableView":{"role":"symbol","title":"tableView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"}],"abstract":[{"type":"text","text":"The table view that displays the result list."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/tableView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/tableview"},"doc://com.microblink.ProductRecognition/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusItem"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/cardShownHeight":{"role":"symbol","title":"cardShownHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardShownHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The ideal height of the card view when the result list is being shown."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/cardShownHeight","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/cardshownheight"},"doc://com.microblink.ProductRecognition/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAccessibilityIdentification"},"doc://com.microblink.ProductRecognition/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/draggingCard":{"role":"symbol","title":"draggingCard","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"draggingCard"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The block to execute when the top of the card view is being dragged."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/draggingCard","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/draggingcard"},"doc://com.microblink.ProductRecognition/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIResponderStandardEditActions"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/UITableViewDelegate-Implementations":{"role":"collectionGroup","title":"UITableViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/UITableViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/uitableviewdelegate-implementations"},"doc://com.microblink.ProductRecognition/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIUserActivityRestoring"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/didTapCard":{"role":"symbol","title":"didTapCard","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapCard"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The block to execute when the top of the card view is tapped."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/didTapCard","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/didtapcard"},"doc://com.microblink.ProductRecognition/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearance"},"doc://com.microblink.ProductRecognition/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)CALayerDelegate"},"doc://com.microblink.ProductRecognition/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIView"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/products":{"role":"symbol","title":"products","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"products"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ProductInfo","preciseIdentifier":"s:10BlinkShelf11ProductInfoV"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The products displayed on the list."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/products","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/products"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/loadList(of:store:)":{"role":"symbol","title":"loadList(of:store:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ProductInfo","preciseIdentifier":"s:10BlinkShelf11ProductInfoV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"store"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Store","preciseIdentifier":"s:10BlinkShelf5StoreV"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Loads the list of products and promotions to display."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/loadList(of:store:)","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/loadlist(of:store:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView":{"role":"symbol","title":"ResultListView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListView"}],"abstract":[{"type":"text","text":"A view that displays a list of results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListView"}],"url":"\/documentation\/blinkshelf\/resultlistview"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/cardView":{"role":"symbol","title":"cardView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view that contains the result list"}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/cardView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/cardview"},"doc://com.microblink.ProductRecognition/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UIKit.UITableViewDelegate","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITableViewDelegate"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultListView/summaryText":{"role":"symbol","title":"summaryText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"summaryText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The text to display when the result list is not showing."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/summaryText","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultlistview\/summarytext"},"doc://com.microblink.ProductRecognition/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIDynamicItem"},"doc://com.microblink.ProductRecognition/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusEnvironment"},"doc://com.microblink.ProductRecognition/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.microblink.ProductRecognition/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UICoordinateSpace"},"doc://com.microblink.ProductRecognition/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.microblink.ProductRecognition/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject"},"doc://com.microblink.ProductRecognition/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ResultListView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ResultListView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ResultListView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/init(frame:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/layoutSubviews()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/UITableViewDataSource-Implementations","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultListView\/UITableViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultListView~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultListView~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultListView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultListView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultListView\/title","value":"ResultListView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultListView\/fragments","value":[{"kind":"identifier","text":"ResultListView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}