{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TrackedDataObjC"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/trackeddataobjc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/trackeddataobjc"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject","doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP","doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/SQ","doc:\/\/com.microblink.ProductRecognition\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC\/init(params:coordinateSystemCenterX:coordinateSystemCenterY:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC\/coordinateSystemCenterX","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC\/coordinateSystemCenterY","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC\/itemsTrackingData"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TrackedDataObjC"}],"title":"TrackedDataObjC","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)TrackedDataObjC","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"TrackedDataObjC"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf"]]},"references":{"doc://com.microblink.ProductRecognition/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/TrackedDataObjC/coordinateSystemCenterX":{"role":"symbol","title":"coordinateSystemCenterX","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinateSystemCenterX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC\/coordinateSystemCenterX","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"coordinateSystemCenterX"}],"url":"\/documentation\/blinkshelf\/trackeddataobjc\/coordinatesystemcenterx"},"doc://com.microblink.ProductRecognition/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SQ"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/TrackedDataObjC/itemsTrackingData":{"role":"symbol","title":"itemsTrackingData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemsTrackingData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Item2dTrackingDataObjC","preciseIdentifier":"c:objc(cs)Item2dTrackingDataObjC"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC\/itemsTrackingData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"itemsTrackingData"}],"url":"\/documentation\/blinkshelf\/trackeddataobjc\/itemstrackingdata"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP"},"doc://com.microblink.ProductRecognition/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(cs)NSObject"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/TrackedDataObjC/coordinateSystemCenterY":{"role":"symbol","title":"coordinateSystemCenterY","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinateSystemCenterY"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC\/coordinateSystemCenterY","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"coordinateSystemCenterY"}],"url":"\/documentation\/blinkshelf\/trackeddataobjc\/coordinatesystemcentery"},"doc://com.microblink.ProductRecognition/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/TrackedDataObjC/init(params:coordinateSystemCenterX:coordinateSystemCenterY:)":{"role":"symbol","title":"init(params:coordinateSystemCenterX:coordinateSystemCenterY:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Item2dTrackingDataObjC","preciseIdentifier":"c:objc(cs)Item2dTrackingDataObjC"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"coordinateSystemCenterX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"coordinateSystemCenterY"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC\/init(params:coordinateSystemCenterX:coordinateSystemCenterY:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithParams:coordinateSystemCenterX:coordinateSystemCenterY:"}],"url":"\/documentation\/blinkshelf\/trackeddataobjc\/init(params:coordinatesystemcenterx:coordinatesystemcentery:)"},"doc://com.microblink.ProductRecognition/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SH"},"doc://com.microblink.ProductRecognition/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/TrackedDataObjC":{"role":"symbol","title":"TrackedDataObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TrackedDataObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TrackedDataObjC"}],"url":"\/documentation\/blinkshelf\/trackeddataobjc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TrackedDataObjC"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TrackedDataObjC"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TrackedDataObjC"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC\/coordinateSystemCenterX","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC\/coordinateSystemCenterY","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC\/itemsTrackingData"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC\/init(params:coordinateSystemCenterX:coordinateSystemCenterY:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TrackedDataObjC"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1TrackedDataObjC~1coordinateSystemCenterX\/title","value":"coordinateSystemCenterX"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1TrackedDataObjC~1coordinateSystemCenterX\/fragments","value":[{"kind":"identifier","text":"coordinateSystemCenterX"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1TrackedDataObjC~1itemsTrackingData\/title","value":"itemsTrackingData"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1TrackedDataObjC~1itemsTrackingData\/fragments","value":[{"kind":"identifier","text":"itemsTrackingData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1TrackedDataObjC~1coordinateSystemCenterY\/title","value":"coordinateSystemCenterY"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1TrackedDataObjC~1coordinateSystemCenterY\/fragments","value":[{"kind":"identifier","text":"coordinateSystemCenterY"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1TrackedDataObjC~1init(params:coordinateSystemCenterX:coordinateSystemCenterY:)\/title","value":"initWithParams:coordinateSystemCenterX:coordinateSystemCenterY:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1TrackedDataObjC~1init(params:coordinateSystemCenterX:coordinateSystemCenterY:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParams:coordinateSystemCenterX:coordinateSystemCenterY:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1TrackedDataObjC\/title","value":"TrackedDataObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1TrackedDataObjC\/fragments","value":[{"kind":"identifier","text":"TrackedDataObjC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}