{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"V_MOBILE_1_0_0"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/detectorversionobjc\/v_mobile_1_0_0"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/detectorversionobjc\/v_mobile_1_0_0"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectorVersionObjC\/V_MOBILE_1_0_0","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"V_MOBILE_1_0_0"}],"title":"DetectorVersionObjC.V_MOBILE_1_0_0","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@DetectorVersionObjC@V_MOBILE_1_0_0","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"V_MOBILE_1_0_0"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectorVersionObjC"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/DetectorVersionObjC/V_MOBILE_1_0_0":{"role":"symbol","title":"DetectorVersionObjC.V_MOBILE_1_0_0","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"V_MOBILE_1_0_0"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectorVersionObjC\/V_MOBILE_1_0_0","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"V_MOBILE_1_0_0"}],"url":"\/documentation\/blinkshelf\/detectorversionobjc\/v_mobile_1_0_0"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/DetectorVersionObjC":{"role":"symbol","title":"DetectorVersionObjC","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectorVersionObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/DetectorVersionObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectorVersionObjC"}],"url":"\/documentation\/blinkshelf\/detectorversionobjc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"V_MOBILE_1_0_0"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"V_MOBILE_1_0_0"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"V_MOBILE_1_0_0"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectorVersionObjC~1V_MOBILE_1_0_0\/title","value":"V_MOBILE_1_0_0"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectorVersionObjC~1V_MOBILE_1_0_0\/fragments","value":[{"kind":"identifier","text":"V_MOBILE_1_0_0"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectorVersionObjC\/title","value":"DetectorVersionObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1DetectorVersionObjC\/fragments","value":[{"kind":"identifier","text":"DetectorVersionObjC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}