{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"counterClockwise90"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/cvpixelbufferorientation\/counterclockwise90"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/cvpixelbufferorientation\/counterclockwise90"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/CVPixelBufferOrientation\/counterClockwise90","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"counterClockwise90"}],"title":"CVPixelBufferOrientation.counterClockwise90","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@CVPixelBufferOrientation@CVPixelBufferOrientationCounterClockwise90","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"CVPixelBufferOrientationCounterClockwise90"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/CVPixelBufferOrientation"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/CVPixelBufferOrientation/counterClockwise90":{"role":"symbol","title":"CVPixelBufferOrientation.counterClockwise90","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"counterClockwise90"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/CVPixelBufferOrientation\/counterClockwise90","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CVPixelBufferOrientationCounterClockwise90"}],"url":"\/documentation\/blinkshelf\/cvpixelbufferorientation\/counterclockwise90"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/CVPixelBufferOrientation":{"role":"symbol","title":"CVPixelBufferOrientation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVPixelBufferOrientation"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/CVPixelBufferOrientation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CVPixelBufferOrientation"}],"url":"\/documentation\/blinkshelf\/cvpixelbufferorientation"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CVPixelBufferOrientationCounterClockwise90"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CVPixelBufferOrientationCounterClockwise90"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CVPixelBufferOrientationCounterClockwise90"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1CVPixelBufferOrientation~1counterClockwise90\/title","value":"CVPixelBufferOrientationCounterClockwise90"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1CVPixelBufferOrientation~1counterClockwise90\/fragments","value":[{"kind":"identifier","text":"CVPixelBufferOrientationCounterClockwise90"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1CVPixelBufferOrientation\/title","value":"CVPixelBufferOrientation"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1CVPixelBufferOrientation\/fragments","value":[{"kind":"identifier","text":"CVPixelBufferOrientation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}