{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noRotation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/cvpixelbufferorientation\/norotation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/cvpixelbufferorientation\/norotation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/CVPixelBufferOrientation\/noRotation","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noRotation"}],"title":"CVPixelBufferOrientation.noRotation","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@CVPixelBufferOrientation@CVPixelBufferOrientationNoRotation","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"CVPixelBufferOrientationNoRotation"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/CVPixelBufferOrientation"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/CVPixelBufferOrientation/noRotation":{"role":"symbol","title":"CVPixelBufferOrientation.noRotation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noRotation"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/CVPixelBufferOrientation\/noRotation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CVPixelBufferOrientationNoRotation"}],"url":"\/documentation\/blinkshelf\/cvpixelbufferorientation\/norotation"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/CVPixelBufferOrientation":{"role":"symbol","title":"CVPixelBufferOrientation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVPixelBufferOrientation"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/CVPixelBufferOrientation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CVPixelBufferOrientation"}],"url":"\/documentation\/blinkshelf\/cvpixelbufferorientation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CVPixelBufferOrientationNoRotation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CVPixelBufferOrientationNoRotation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CVPixelBufferOrientationNoRotation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1CVPixelBufferOrientation~1noRotation\/title","value":"CVPixelBufferOrientationNoRotation"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1CVPixelBufferOrientation~1noRotation\/fragments","value":[{"kind":"identifier","text":"CVPixelBufferOrientationNoRotation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1CVPixelBufferOrientation\/title","value":"CVPixelBufferOrientation"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1CVPixelBufferOrientation\/fragments","value":[{"kind":"identifier","text":"CVPixelBufferOrientation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}