{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadResultBanners"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"resultIndicator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultIndicator","preciseIdentifier":"c:@M@BlinkShelf@objc(cs)ResultIndicator","text":"ResultIndicator"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"resultIndicator","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result indicator that, when selected, will display the result banners."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/resultbannerscrollview\/loadresultbanners(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBannerScrollView\/loadResultBanners(for:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Loads the result banners to be displayed."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadResultBanners"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResultIndicator","preciseIdentifier":"c:@M@BlinkShelf@objc(cs)ResultIndicator"},{"kind":"text","text":"?)"}],"title":"loadResultBanners(for:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:10BlinkShelf22ResultBannerScrollViewC04loadC7Banners3foryAA0C9IndicatorCSg_tF","modules":[{"name":"BlinkShelf"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBannerScrollView"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBannerScrollView":{"role":"symbol","title":"ResultBannerScrollView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBannerScrollView"}],"abstract":[{"type":"text","text":"A scrollable view that displays multiple result banners."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBannerScrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBannerScrollView"}],"url":"\/documentation\/blinkshelf\/resultbannerscrollview"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBannerScrollView/loadResultBanners(for:)":{"role":"symbol","title":"loadResultBanners(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadResultBanners"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResultIndicator","preciseIdentifier":"c:@M@BlinkShelf@objc(cs)ResultIndicator"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Loads the result banners to be displayed."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBannerScrollView\/loadResultBanners(for:)","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultbannerscrollview\/loadresultbanners(for:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultIndicator":{"role":"symbol","title":"ResultIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultIndicator"}],"abstract":[{"type":"text","text":"A view that indicates a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultIndicator"}],"url":"\/documentation\/blinkshelf\/resultindicator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultBannerScrollView\/title","value":"ResultBannerScrollView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultBannerScrollView\/fragments","value":[{"kind":"identifier","text":"ResultBannerScrollView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultIndicator\/title","value":"ResultIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultIndicator\/fragments","value":[{"kind":"identifier","text":"ResultIndicator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}