{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"storeName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/scanagainstoreview\/init(storename:frame:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ScanAgainStoreView\/init(storeName:frame:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"storeName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"title":"init(storeName:frame:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:10BlinkShelf18ScanAgainStoreViewC9storeName5frameACSS_So6CGRectVtcfc","modules":[{"name":"BlinkShelf"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ScanAgainStoreView"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ScanAgainStoreView/init(storeName:frame:)":{"role":"symbol","title":"init(storeName:frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"storeName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ScanAgainStoreView\/init(storeName:frame:)","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/scanagainstoreview\/init(storename:frame:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ScanAgainStoreView":{"role":"symbol","title":"ScanAgainStoreView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanAgainStoreView"}],"abstract":[{"type":"text","text":"A specialized label for the for placement in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultVC"}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ScanAgainStoreView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScanAgainStoreView"}],"url":"\/documentation\/blinkshelf\/scanagainstoreview"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultVC":{"role":"symbol","title":"ResultVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultVC"}],"abstract":[{"type":"text","text":"A view controller that displays the result of the scanned image."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultVC"}],"url":"\/documentation\/blinkshelf\/resultvc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ScanAgainStoreView\/title","value":"ScanAgainStoreView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ScanAgainStoreView\/fragments","value":[{"kind":"identifier","text":"ScanAgainStoreView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultVC\/title","value":"ResultVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultVC\/fragments","value":[{"kind":"identifier","text":"ResultVC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}