{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getContoursImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withRotation"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/CVPixelBufferOrientation","preciseIdentifier":"c:@E@CVPixelBufferOrientation","text":"CVPixelBufferOrientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/featuresextractorobjc\/getcontoursimage(for:withrotation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/featuresextractorobjc\/getcontoursimage(for:withrotation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/FeaturesExtractorObjC\/getContoursImage(for:withRotation:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getContoursImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withRotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBufferOrientation","preciseIdentifier":"c:@E@CVPixelBufferOrientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"title":"getContoursImage(for:withRotation:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)FeaturesExtractorObjC(im)getContoursImageForBuffer:withRotation:","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"getContoursImageForBuffer:withRotation:"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/FeaturesExtractorObjC"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/FeaturesExtractorObjC/getContoursImage(for:withRotation:)":{"role":"symbol","title":"getContoursImage(for:withRotation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getContoursImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withRotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBufferOrientation","preciseIdentifier":"c:@E@CVPixelBufferOrientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/FeaturesExtractorObjC\/getContoursImage(for:withRotation:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getContoursImageForBuffer:withRotation:"}],"url":"\/documentation\/blinkshelf\/featuresextractorobjc\/getcontoursimage(for:withrotation:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/CVPixelBufferOrientation":{"role":"symbol","title":"CVPixelBufferOrientation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVPixelBufferOrientation"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/CVPixelBufferOrientation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CVPixelBufferOrientation"}],"url":"\/documentation\/blinkshelf\/cvpixelbufferorientation"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/FeaturesExtractorObjC":{"role":"symbol","title":"FeaturesExtractorObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeaturesExtractorObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/FeaturesExtractorObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeaturesExtractorObjC"}],"url":"\/documentation\/blinkshelf\/featuresextractorobjc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getContoursImageForBuffer:withRotation:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getContoursImageForBuffer:withRotation:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getContoursImageForBuffer:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"__CVBuffer","preciseIdentifier":"c:@S@__CVBuffer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":" "},{"kind":"identifier","text":"withRotation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/CVPixelBufferOrientation","preciseIdentifier":"c:@E@CVPixelBufferOrientation","text":"CVPixelBufferOrientation"},{"kind":"text","text":")"},{"kind":"internalParam","text":"rotation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1FeaturesExtractorObjC~1getContoursImage(for:withRotation:)\/title","value":"getContoursImageForBuffer:withRotation:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1FeaturesExtractorObjC~1getContoursImage(for:withRotation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getContoursImageForBuffer:withRotation:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1CVPixelBufferOrientation\/title","value":"CVPixelBufferOrientation"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1CVPixelBufferOrientation\/fragments","value":[{"kind":"identifier","text":"CVPixelBufferOrientation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1FeaturesExtractorObjC\/title","value":"FeaturesExtractorObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1FeaturesExtractorObjC\/fragments","value":[{"kind":"identifier","text":"FeaturesExtractorObjC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}