{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromBGRBytes"},{"kind":"text","text":" "},{"kind":"internalParam","text":"srcBgrBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/imageutilsobjcpp\/createdata(frombgrbytes:count:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/imageutilsobjcpp\/createdata(frombgrbytes:count:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageUtilsObjCpp\/createData(fromBGRBytes:count:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromBGRBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"title":"createData(fromBGRBytes:count:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ImageUtilsObjCpp(cm)createDataFromBGRBytes:count:","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"createDataFromBGRBytes:count:"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageUtilsObjCpp"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageUtilsObjCpp/createData(fromBGRBytes:count:)":{"role":"symbol","title":"createData(fromBGRBytes:count:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromBGRBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageUtilsObjCpp\/createData(fromBGRBytes:count:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createDataFromBGRBytes:count:"}],"url":"\/documentation\/blinkshelf\/imageutilsobjcpp\/createdata(frombgrbytes:count:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ImageUtilsObjCpp":{"role":"symbol","title":"ImageUtilsObjCpp","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageUtilsObjCpp"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ImageUtilsObjCpp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageUtilsObjCpp"}],"url":"\/documentation\/blinkshelf\/imageutilsobjcpp"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createDataFromBGRBytes:count:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createDataFromBGRBytes:count:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createDataFromBGRBytes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"uint8_t","preciseIdentifier":"c:@T@uint8_t"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"srcBgrBytes"},{"kind":"text","text":" "},{"kind":"identifier","text":"count:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":")"},{"kind":"internalParam","text":"count"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageUtilsObjCpp~1createData(fromBGRBytes:count:)\/title","value":"createDataFromBGRBytes:count:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageUtilsObjCpp~1createData(fromBGRBytes:count:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createDataFromBGRBytes:count:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageUtilsObjCpp\/title","value":"ImageUtilsObjCpp"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ImageUtilsObjCpp\/fragments","value":[{"kind":"identifier","text":"ImageUtilsObjCpp"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}