{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultBannerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBannerScrollView","preciseIdentifier":"c:@M@BlinkShelf@objc(cs)ResultBannerScrollView","text":"ResultBannerScrollView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/resultvc\/resultbannerview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultVC\/resultBannerView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The scrollable view that displays multiple result banners."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultBannerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResultBannerScrollView","preciseIdentifier":"c:@M@BlinkShelf@objc(cs)ResultBannerScrollView"}],"title":"resultBannerView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10BlinkShelf8ResultVCC16resultBannerViewAA0cf6ScrollG0Cvp","modules":[{"name":"BlinkShelf"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultVC"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultVC/resultBannerView":{"role":"symbol","title":"resultBannerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultBannerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResultBannerScrollView","preciseIdentifier":"c:@M@BlinkShelf@objc(cs)ResultBannerScrollView"}],"abstract":[{"type":"text","text":"The scrollable view that displays multiple result banners."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultVC\/resultBannerView","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf\/resultvc\/resultbannerview"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultVC":{"role":"symbol","title":"ResultVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultVC"}],"abstract":[{"type":"text","text":"A view controller that displays the result of the scanned image."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultVC"}],"url":"\/documentation\/blinkshelf\/resultvc"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/ResultBannerScrollView":{"role":"symbol","title":"ResultBannerScrollView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBannerScrollView"}],"abstract":[{"type":"text","text":"A scrollable view that displays multiple result banners."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/ResultBannerScrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBannerScrollView"}],"url":"\/documentation\/blinkshelf\/resultbannerscrollview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultVC\/title","value":"ResultVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultVC\/fragments","value":[{"kind":"identifier","text":"ResultVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultBannerScrollView\/title","value":"ResultBannerScrollView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1ResultBannerScrollView\/fragments","value":[{"kind":"identifier","text":"ResultBannerScrollView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}