{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoOutput"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willCapturePhotoFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"resolvedSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureResolvedPhotoSettings","preciseIdentifier":"c:objc(cs)AVCaptureResolvedPhotoSettings"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/singlephotovc\/photooutput(_:willcapturephotofor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/singlephotovc\/photooutput(_:willcapturephotofor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/SinglePhotoVC\/photoOutput(_:willCapturePhotoFor:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AVCapturePhotoCaptureDelegate.photoOutput(_:willCapturePhotoFor:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoOutput"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willCapturePhotoFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureResolvedPhotoSettings","preciseIdentifier":"c:objc(cs)AVCaptureResolvedPhotoSettings"},{"kind":"text","text":")"}],"title":"photoOutput(_:willCapturePhotoFor:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@BlinkShelf@objc(cs)SinglePhotoVC(im)captureOutput:willCapturePhotoForResolvedSettings:","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"captureOutput:willCapturePhotoForResolvedSettings:"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/SinglePhotoVC"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/SinglePhotoVC/photoOutput(_:willCapturePhotoFor:)":{"role":"symbol","title":"photoOutput(_:willCapturePhotoFor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoOutput"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willCapturePhotoFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureResolvedPhotoSettings","preciseIdentifier":"c:objc(cs)AVCaptureResolvedPhotoSettings"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/SinglePhotoVC\/photoOutput(_:willCapturePhotoFor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureOutput:willCapturePhotoForResolvedSettings:"}],"url":"\/documentation\/blinkshelf\/singlephotovc\/photooutput(_:willcapturephotofor:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/SinglePhotoVC":{"role":"symbol","title":"SinglePhotoVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SinglePhotoVC"}],"abstract":[{"type":"text","text":"A view controller that manages the interface for capturing a single photo to be used for product detection."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/SinglePhotoVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SinglePhotoVC"}],"url":"\/documentation\/blinkshelf\/singlephotovc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"captureOutput:willCapturePhotoForResolvedSettings:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureOutput:willCapturePhotoForResolvedSettings:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"captureOutput:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"output"},{"kind":"text","text":" "},{"kind":"identifier","text":"willCapturePhotoForResolvedSettings:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCaptureResolvedPhotoSettings","preciseIdentifier":"c:objc(cs)AVCaptureResolvedPhotoSettings"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"resolvedSettings"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1SinglePhotoVC~1photoOutput(_:willCapturePhotoFor:)\/title","value":"captureOutput:willCapturePhotoForResolvedSettings:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1SinglePhotoVC~1photoOutput(_:willCapturePhotoFor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureOutput:willCapturePhotoForResolvedSettings:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1SinglePhotoVC\/title","value":"SinglePhotoVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1SinglePhotoVC\/fragments","value":[{"kind":"identifier","text":"SinglePhotoVC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}