{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinateSystemCenterX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/trackeddataobjc\/coordinatesystemcenterx"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/trackeddataobjc\/coordinatesystemcenterx"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC\/coordinateSystemCenterX","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinateSystemCenterX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"title":"coordinateSystemCenterX","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)TrackedDataObjC(py)coordinateSystemCenterX","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"coordinateSystemCenterX"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/TrackedDataObjC":{"role":"symbol","title":"TrackedDataObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TrackedDataObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TrackedDataObjC"}],"url":"\/documentation\/blinkshelf\/trackeddataobjc"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/TrackedDataObjC/coordinateSystemCenterX":{"role":"symbol","title":"coordinateSystemCenterX","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinateSystemCenterX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/TrackedDataObjC\/coordinateSystemCenterX","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"coordinateSystemCenterX"}],"url":"\/documentation\/blinkshelf\/trackeddataobjc\/coordinatesystemcenterx"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"coordinateSystemCenterX"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"coordinateSystemCenterX"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinateSystemCenterX"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1TrackedDataObjC\/title","value":"TrackedDataObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1TrackedDataObjC\/fragments","value":[{"kind":"identifier","text":"TrackedDataObjC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1TrackedDataObjC~1coordinateSystemCenterX\/title","value":"coordinateSystemCenterX"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1TrackedDataObjC~1coordinateSystemCenterX\/fragments","value":[{"kind":"identifier","text":"coordinateSystemCenterX"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}