{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aDecoder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/gradientbackgroundview\/init(coder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/gradientbackgroundview\/init(coder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/GradientBackgroundView\/init(coder:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"title":"init(coder:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@BlinkShelf@objc(cs)GradientBackgroundView(im)initWithCoder:","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/GradientBackgroundView"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/GradientBackgroundView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/GradientBackgroundView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/blinkshelf\/gradientbackgroundview\/init(coder:)"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/GradientBackgroundView":{"role":"symbol","title":"GradientBackgroundView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientBackgroundView"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/GradientBackgroundView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GradientBackgroundView"}],"url":"\/documentation\/blinkshelf\/gradientbackgroundview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCoder:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aDecoder"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1GradientBackgroundView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1GradientBackgroundView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1GradientBackgroundView\/title","value":"GradientBackgroundView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1GradientBackgroundView\/fragments","value":[{"kind":"identifier","text":"GradientBackgroundView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}