{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":" "},{"kind":"internalParam","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinkshelf\/feature\/init(params:y:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkshelf\/feature\/init(params:y:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Feature\/init(params:y:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"title":"init(params:y:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)Feature(im)initWithParams:y:","modules":[{"name":"BlinkShelf"}],"navigatorTitle":[{"kind":"identifier","text":"initWithParams:y:"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Feature"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/Feature":{"role":"symbol","title":"Feature","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Feature"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Feature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Feature"}],"url":"\/documentation\/blinkshelf\/feature"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf":{"role":"collection","title":"BlinkShelf","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf","kind":"symbol","type":"topic","url":"\/documentation\/blinkshelf"},"doc://com.microblink.ProductRecognition/documentation/BlinkShelf/Feature/init(params:y:)":{"role":"symbol","title":"init(params:y:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/BlinkShelf\/Feature\/init(params:y:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithParams:y:"}],"url":"\/documentation\/blinkshelf\/feature\/init(params:y:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithParams:y:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParams:y:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":")"},{"kind":"internalParam","text":"x"},{"kind":"text","text":" "},{"kind":"identifier","text":"y:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":")"},{"kind":"internalParam","text":"y"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Feature\/title","value":"Feature"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Feature\/fragments","value":[{"kind":"identifier","text":"Feature"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Feature~1init(params:y:)\/title","value":"initWithParams:y:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1BlinkShelf~1Feature~1init(params:y:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParams:y:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}